CREATE TABLE IF NOT EXISTS raw.credit_applications (
    application_id TEXT,
    customer_id TEXT,
    application_date TEXT,
    uf TEXT,
    channel TEXT,
    age TEXT,
    gender TEXT,
    education TEXT,
    employment_type TEXT,
    months_employed TEXT,
    monthly_income TEXT,
    bank_relationship_months TEXT,
    marital_status TEXT,
    dependents TEXT,
    housing_status TEXT,
    credit_history_months TEXT,
    previous_loans TEXT,
    previous_defaults TEXT,
    bureau_inquiries_90d TEXT,
    open_credit_lines TEXT,
    credit_utilization TEXT,
    delinquency_12m TEXT,
    avg_payment_delay_days TEXT,
    monthly_existing_debt TEXT,
    requested_amount TEXT,
    loan_purpose TEXT,
    term_months TEXT,
    estimated_installment TEXT,
    debt_to_income TEXT,
    digital_behavior_score TEXT,
    device_age_months TEXT,
    email_age_months TEXT,
    phone_verified TEXT,
    document_consistency TEXT,
    ip_risk_score TEXT,
    credit_score_internal TEXT,
    risk_band TEXT,
    approved TEXT,
    approved_amount TEXT,
    interest_rate_monthly TEXT,
    default_90d TEXT,
    fraud_confirmed TEXT,

    source_file TEXT DEFAULT 'fintech_credit_risk_dataset.csv',
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);